var appConstants = {
  GET_MOVIE_LIST_SUCCESS: 'GET_MOVIE_LIST_SUCCESS',
  GET_MOVIE_LIST_FAILED: 'GET_MOVIE_LIST_FAILED',
  GET_ACTOR_LIST_SUCCESS: 'GET_ACTOR_LIST_SUCCESS',
  GET_ACTOR_LIST_FAILED: 'GET_ACTOR_LIST_FAILED',
};

module.exports = appConstants;